### ISSUE TITLE
Issues with script,

### ISSUE THREAD

**Issue by Draven0** [FingerlessGlov3s/OPNsensePIAWireguard#1]
When running script i get

 /conf/PIAWireguard.py debug
searchServer request failed non 200 status code - listing wireguard instances

Permissions are set correctly, 
running OPNSense 20.7.4
Wireguard plugin installed,
correct API keys in place.

**Comment by Draven0** [comment]
This appears to have been my own issue, missing a " at the start of the API key, however now i'm getting

wireguardserver addKey request failed non 200 status code - Trying to add instance public key to server in exchnage for connection information

**Comment by FingerlessGlov3s** [comment]
Check your OPNsense API key and the user's permissions (screenshot below) also the user variable opnsenseURL  have you amended that to use the port that your OPNsense instance uses? Default install would be 'https://127.0.0.1:443' (you can omit the port if its 443 of course.)

By default OPNsense uses port 443 for the web interface, but I always change it to 8443, so that's why its 8443 in the script.


![image](https://user-images.githubusercontent.com/3495647/99644442-da638f80-2a45-11eb-8e41-d9414a22b484.png)

**Comment by Draven0** [comment]
Thank you for your response, i managed to work all that out, but i'm now getting the above error.  I've double confirmed all the permissions and the correct API key in place. 

But i cannot see the cause of the

wireguardserver addKey request failed non 200 status code - Trying to add instance public key to server in exchnage for connection information

**Comment by Draven0** [comment]
Please ignore me, i've managed to work it out successfullly ran the script

**Comment by FingerlessGlov3s** [comment]
What was the issue?

Incase others come across this issue on github

**Comment by Draven0** [comment]
I simply removed all of the ports from the url

So just put

https://127.0.0.1

it didn't seem to work when i put https://127.0.0.1:443 i have no idea why. I then confirmed that everything else was correct and ran the script and it worked.

**Comment by FingerlessGlov3s** [comment]
Glad to hear it worked, any more questions or issues just say.

I shall close this issue.
