### ISSUE TITLE
I have to add a static route

### ISSUE THREAD

**Issue by kumy** [FingerlessGlov3s/OPNsensePIAWireguard#2]
First thanks for your scripts!

I'm facing a problem, after the connection/server change I need to add (or update) a _missing?_ static route to the upstream WG server endpoint.

On WG session establishment, my (internet) routes are as bellow, and the tunnel doesn't work.
```
Internet:
Destination        Gateway            Flags     Netif Expire
default            10.28.128.1        UGS         wg0
10.28.128.1        wg0                UHS         wg0
10.28.179.205      link#14            UH          wg0
127.0.0.1          link#7             UH          lo0
[…] 
```
I have to manually create a static route, which I have to maintain myself in order to obtain :
```
Internet:
Destination        Gateway            Flags     Netif Expire
default            10.28.128.1        UGS         wg0
10.28.128.1        wg0                UHS         wg0
10.28.179.205      link#14            UH          wg0
127.0.0.1          link#7             UH          lo0
143.244.57.157/32  192.168.2.1        UGS         re0   # <--- added
```

The created WG local configuration has the `Disable Routes` ticked. The associated comment "This will prevent installing routes. Usually you only enable this to do own routing decisions via a local gateway and gateway rules.". I suppose this is why such route is not created for this tunnel.

I gave `PIAWireguard.py`  script a look and didn't found a part for automatic route management.

Do I miss something?
Thanks!

**Comment by FingerlessGlov3s** [comment]
Hey,

I'm not sure why your default route after running the script is via WireGuard, because it shouldn't be. What should happen is the routing tables get two new routes. PIA's WG gateway IP and the IP of your assigned IP. Then you use the gateway you created to create Policy based routing rules (Firewall Rules).

I followed the guide on a test device this weekend, to making sure the guide works correctly, without error on OPNsense 20.7.7_1. Which update of OPNsense are you on?
I've also got it running on 3 other production OPNsense Firewalls without this issue occurring, so very strange.

Ticking "Disable Routes" is basically a requirement for this to all work correctly, otherwise you'll have routing issues with the Firewall itself, like your getting.

Example of my routes (taken the local network ones out)
```
Internet:
Destination        Gateway            Flags     Netif Expire
default            80-46-0-1.dynamic. UGS        igb0
10.56.128.1        wg1                UHS         wg1  # <--- added by WireGuard (PIA Gateway)
10.56.232.72       link#19            UH          wg1 # <--- added by WireGuard (Your PIA assigned IP)
80.46.0.0/20       link#1             U          igb0
80.46.1.132        link#1             UHS      
```

FingerlessGloves

**Comment by kumy** [comment]
Thanks for your fast response. I wish all my ipv4 traffic to go through the vpn, so the default rule seems to make sense for me. We seems to have different configurations/goals, isn't it?

**Comment by kumy** [comment]
I may try to add a way to conditionally manage a static route in your script. I've never worked with the OPNsense api before (comming from PF since a few days). It may take me a long time :/ Do you have some input or tips to implement that? Thanks

**Comment by FingerlessGlov3s** [comment]
I think your going about it incorrectly atleast in my eyes, you could probably fudge something to get the routes on the OPNsense device to go via PIA but the issue would then be, if the tunnel drops the routes wouldn't remove themselves because of how WireGuard works, so when the script needs to get a new server it can't contact PIA to get another WireGuard server, which would happen at least every 2 months, due to PIA updating and restarting servers roughly in that period.

This is basic overview of how I would set this up to keep your devices using PIA only without messing with OPNsense too much.
Revert the PIA WireGuard setup back to how it is in the Guide/Script.

Go in to OPNsense WebUI, Firewall: NAT: Outbound. Change the Mode of the outbound NAT to manual.
Now create a New NAT rule, similar to the one below
- Interface: WAN_PIAWG
- SRC: internal network (I use ALIAS but you can use LAN network), 
- DEST: ANY
- Translation / target: Interface Address
- Leave the rest default

![image](https://user-images.githubusercontent.com/3495647/105101204-69247500-5aa6-11eb-84da-7630406e5675.png)

Now on your LAN rules, on the rule which allows traffic to the internet, set the gateway to WAN_PIAWG_IPv4.

Now because you don't have a NAT rule to NAT traffic from your LAN to WAN, you remove the risk of leaking if the PIA VPN tunnel comes down.
You should have 2 firewall rules, that says something like, if you want to restrict it more that's up to you.
Rule 1
- SRC: LAN Network
- DEST LAN Network
- Gateway: Default
- Description: All Lan to LAN

Rule 2
- SRC: LAN Network
- DEST !LAN Network
- Gateway: WAN_PIAWG_IPv4
- Description: All Internet traffic.

Make sure the rules are in this order.

I hope this idea makes sense, very basic way of having a network only use PIA for Internet access.

FingerlessGloves

**Comment by kumy** [comment]
Thanks :+1: , I'll give it a try, probably tomorrow. I'll keep you informed.

**Comment by FingerlessGlov3s** [comment]
Sounds good, any questions just ask.

Make sure you got your phone's internet to hand encase you break something 🤭

Night

**Comment by kumy** [comment]
So, I've simply enabled the automatic gateway management by wireguard (https://github.com/kumy/OPNsensePIAWireguard/commit/9269e404df6f75d9afa19ea588df0f63dde070c8) and it now work as I wish.

My routes are now:
```bash
# (I have 2 tunnels)
root@gw:~ # netstat -rn4
Routing tables

Internet:
Destination        Gateway            Flags     Netif Expire
0.0.0.0/1          wg0                US          wg0
default            192.168.2.1        UGS         re0
10.8.168.83        link#14            UH          wg0
x.x.x.x            192.168.2.1        UGHS        re0
127.0.0.1          link#7             UH          lo0
128.0.0.0/1        wg0                US          wg0
y.y.y.y/32         192.168.2.1        UGS         re0
192.168.2.0/24     link#1             U           re0
192.168.2.101      link#1             UHS         lo0
192.168.125.0/24   link#2             U           re1
192.168.125.253    link#2             UHS         lo0
192.168.126.0/24   link#10            U      ath0_wla
192.168.126.1      link#10            UHS         lo0
192.168.200.1/32   wg1                US          wg1
192.168.200.2      link#13            UH          wg1
root@gw:~ # 
```

I have not tested your last solution, but it seems a bit overkill to define the `gateway` in each of my rules…
Feel free to close the issue if you wish, thanks again for this project and for your time.

**Comment by FingerlessGlov3s** [comment]
You only need to define the gateway once in your last rule, which should be the rule that lets your clients to the internet.

Yeah that change should do the trick.
How are you going to cater for the issue of contacting the PIA server list when the tunnel up but no handshakes or traffic?

**Comment by kumy** [comment]
> How are you going to cater for the issue of contacting the PIA server list when the tunnel up but no handshakes or traffic?

I do not need to handle it as from what I've seen, it is automatically managed by wg. The route swap seems done only when handshake is valid (and restored when tunnel goes down). I had this conf on my other vpn since some weeks, without problem (but I manage the other side of the tunnel). If I encounter problems I'll report it here.

**Comment by FingerlessGlov3s** [comment]
Cool sounds good, glad it's working 🙂

I shall close the issue 🙂

**Comment by FingerlessGlov3s** [comment]
@kumy, Just a quick one I was just thinking.

What does your routing table look like if you specify a false PIA server and save the wireguard config?

On my WireGuard setup I've got WireGuard peers (RoadWarrior setup) they've had no handshake what so ever but their route is still in the routing table.

How does the WireGuard 0.0.0.0/0 route cope with this?

I do need to create a LAB WireGuard again at somepoint.

**Comment by kumy** [comment]
I'm on another task, I'll check in hour or two, sorry.

**Comment by FingerlessGlov3s** [comment]
Just fired up a test OPNsense, test client. to test this.

The routing doesn't remove itself and the script can't change to a working server cause well there's no internet connection anymore...

Did you say you don't get this issue?

**Comment by kumy** [comment]
I'll check this use case tomorrow, family is still using internet actively…

You want me to test:
- have my OPNsense wireguard connected to a server
- edit the `Endpoint` -> `Endpoint Address` IP to something that doesn't host a WG server
- save / apply / restart wg daemon?
- check routes and connection status

Do we agree on the test case procedure?

**Comment by FingerlessGlov3s** [comment]
Correct and then run the script in debug mode in the CLI, to see what errors are produced.

That method is exactly how I tested it.

**Comment by kumy** [comment]
Effectively this specific use case doesn't work. Are you anticipating that the script may receive a configuration from the API and the remote server is down?

The `PIAWireguard.py` could be updated to handle this case. At the beginning,
- check the internet connectivity to the API
- if it fails and the tunnel is already configured
- then disable the tunnel and process to the rest of the script

What do you think?

**Comment by FingerlessGlov3s** [comment]
Yeah your gonna need to add a ping check, then if no response bring the tunnel down. Of course this check is only needed if your trying to run the script in your setup, so I'm not going to update the main repo. As modifying the default route of the OPNsense in my opinion isn't the best way of setting this up.

I wouldn't worry about PIA API being down, I would think that's in some form of HA setup. Plus PIA have everything service monitored.

Your going to want to implement some form of VPN kill switch for your clients, so when it's brought down, only the OPNsense itself has internet access, though the normal WAN.
